version: "3.8"
services:
  leveldb-server:
    image: ekristen/leveldb
    container_name: leveldb-server
    ports:
      - "2012:2012"
    volumes:
      - ./data/leveldb:/opt/app/db
    environment:
      leveldb_path: "/opt/app/db"
      leveldb_host: "0.0.0.0"
      leveldb_port: 2012
      leveldb_keyEncoding: "utf8"
      leveldb_valueEncoding: "json"
      leveldb_defaultTTL: 0
      leveldb_checkFrequency: 50
